### ISSUE TITLE
Error on building Yaws on Manjaro Linux on Erlang OTP-27

### ISSUE THREAD

**Issue by gvsafronov** [erlyaws/yaws#468] opened 2023-06-14 14:41 UTC
Hi!

I'm compiled the application in Manjaro (linux kernel 6.3.6-1) and  compilation process ended with thee same error:

Artrium@$ /home/grigorii > git clone https://github.com/erlyaws/yaws
Artrium@$ /home/grigorii > cd yaws
Artrium@$ /home/grigorii /riak-riak-3.2.0>autoreconf -fi
Artrium@$ /home/grigorii /riak-riak-3.2.0>./configure
Artrium@$ /home/grigorii /riak-riak-3.2.0>make
Artrium@$ /home/grigorii /riak-riak-3.2.0>make install

Making all in src
make[1]: вход в каталог «/home/grigorii/yaws/src»
  GEN      ../ebin/yaws.app
gawk: cmd. line:1: warning: regexp escape sequence `\@' is not a known regexp operator
  GEN      ../ebin/yaws.appup
  ERLC     ../ebin/yaws.beam
  ERLC     ../ebin/yaws_app.beam
  ERLC     ../ebin/yaws_ticker.beam
  ERLC     ../ebin/yaws_config.beam
compile: warnings being treated as errors
yaws_config.erl:3563:20: file:pid2name/1 is deprecated and will be removed in OTP 27; this functionality is no longer supported
% 3563|     {ok, Config} = file:pid2name(FD),
%     |                    ^

yaws_config.erl:3579:20: file:pid2name/1 is deprecated and will be removed in OTP 27; this functionality is no longer supported
% 3579|     {ok, Config} = file:pid2name(FD),
%     |                    ^

make[1]: *** [Makefile:664: ../ebin/yaws_config.beam] Error 1
make[1]: exit from «/home/grigorii/yaws/src»
make: *** [Makefile:564: all-recursive] Error 1

Please tell me when Erlang OTP 26 support will be implemented?
Thank you

Best regards,
Grigorii Safronov

**Comment by vinoski** [comment] 2023-06-14 16:28
This is a duplicate of #467 .

**Closed by vinoski** 2023-06-14 16:28 UTC
