### ISSUE TITLE
yaws_config.erl:3563:20: file:pid2name/1 is deprecated and will be removed in OTP 27

### ISSUE THREAD

**Issue by alexandrkirilov** [erlyaws/yaws#476] opened 2023-10-16 19:01 UTC
$ make
Making all in src
make[1]: Entering directory '/home/Tools/Yaws/git/src'
  ERLC     ../ebin/yaws.beam
  ERLC     ../ebin/yaws_config.beam
compile: warnings being treated as errors
yaws_config.erl:3563:20: file:pid2name/1 is deprecated and will be removed in OTP 27; this functionality is no longer supported
% 3563|     {ok, Config} = file:pid2name(FD),
%     |                    ^

yaws_config.erl:3579:20: file:pid2name/1 is deprecated and will be removed in OTP 27; this functionality is no longer supported
% 3579|     {ok, Config} = file:pid2name(FD),
%     |                    ^

make[1]: *** [Makefile:664: ../ebin/yaws_config.beam] Error 1
make[1]: Leaving directory '/home/Tools/Yaws/git/src'
make: *** [Makefile:564: all-recursive] Error 1

**Comment by alexandrkirilov** [comment] 2023-10-16 19:04
It's happening on Erlang:
`
$ cat /usr/lib/erlang/releases/RELEASESLEASES
%% coding: utf-8
[{release,"Erlang/OTP","26","14.1.1",
          [{kernel,"9.1","/usr/lib/erlang/lib/kernel-9.1"},
           {stdlib,"5.1.1","/usr/lib/erlang/lib/stdlib-5.1.1"},
           {sasl,"4.2.1","/usr/lib/erlang/lib/sasl-4.2.1"}],
          permanent}].
`

**Comment by vinoski** [comment] 2023-10-16 19:19
Duplicate of #467

**Closed by vinoski** 2023-10-16 19:19 UTC
